contacts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('contact/', views.ContactView.as_view(), name='contact'),
]

events/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('events', views.EventListView.as_view(), name='events'),
    path('events/new', views.EventCreateView.as_view(), name='new-event'),
    path('events/<int:pk>/edit', views.EventUpdateView.as_view(), name='edit-event'),
    path('events/<int:pk>/delete', views.EventDeleteView.as_view(), name='delete-event')
]

mentor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('pages.urls')),
    path('', include('contacts.urls')),
    path('', include('courses.urls')),
    path('', include('trainers.urls')),
    path('', include('events.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about', views.AboutView.as_view(), name='about'),
]

contacts/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name= models.CharField(max_length=100)
    email=models.EmailField(max_length=254) #RFC 2821
    subject=models.CharField(max_length=60)
    message=models.CharField(max_length=512) #Postgres accepts VARCHAR max of 655536
    isAnswered=models.BooleanField(default=False)

    def __str__(self):
        checked=''
        if self.isAnswered:
            checked += "\u2705"
        else:
            checked += "\u23F2"              
       
        return checked + ' ' + self.name +' - '+self.subject

courses/models.py
from django.db import models
from trainers.models import Trainer

# Create your models here.
class Course(models.Model):

    name = models.CharField(max_length=100, help_text="Nombre del curso")
    category = models.ForeignKey('Category', on_delete=models.DO_NOTHING)
    brief = models.TextField(help_text="Presentación del curso")
    text = models.TextField(help_text="Detalle del curso")
    fee = models.DecimalField(max_digits=6, decimal_places=2)
    image = models.ImageField(upload_to="courses")
    seats = models.IntegerField(help_text="Cantidad de plazas")
    schedule = models.CharField(max_length=100, help_text="Días y horarios \
        curso")
    trainer = models.ForeignKey(Trainer, on_delete=models.DO_NOTHING)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=100, help_text="Categoría de Cursos")
    description = models.TextField(help_text="Descripción de la categoría")

    class Meta:
        ordering = ["name"]
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

events/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Event(models.Model):
    # Campos y atributos
    # max_length= 20 — Establece que la longitud máxima del valor
    # de este campo es 20 caracteres.
    # help_text="texto..." — proporciona una etiqueta de texto
    # para mostrar que ayuda.

    title = models.CharField(max_length=100, help_text="Título del evento")
    # Cadena para representar el objeto MyModelName
    # (en el sitio de Admin, etc.)
    text = models.TextField(help_text="Resumen del evento")
    date = models.DateTimeField(help_text="Fecha y hora del evento")
    image = models.ImageField(upload_to="events")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # Metadata
    class Meta:
        # para que el evento más nuevo quedo primero
        ordering = ["-date"]

    # Métodos

    def get_absolute_url(self):
        return reverse("events")
    

    def __str__(self):
        # Cadena para representar el objeto MyModelName
        # (en el sitio de Admin, etc.)
        return self.title

trainers/models.py
from django.db import models

# Create your models here.

class Trainer(models.Model):

    first_name = models.CharField(max_length=100, help_text="Nombre")
    last_name = models.CharField(max_length=100, help_text="Apellido")
    title = models.CharField(max_length=100, help_text="Título")
    brief = models.TextField(help_text="Resumen curricular")
    photo = models.ImageField(upload_to="trainers", help_text="Foto")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta ():
        ordering = ['last_name', 'first_name']

    def __str__(self):
        # Cadena para representar el objeto MyModelName
        # (en el sitio de Admin, etc.)
        return self.last_name + ", " + self.first_name

contacts/forms.py
from django import forms
from .models import Contact

# create a ModelForm
class ContactForm(forms.ModelForm):
    class Meta():
        model = Contact
        fields = ['name', 'email', 'subject', 'message']
          
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control', 'minlength':2,
            'placeholder':'Full name'}),
            'email': forms.EmailInput(attrs={'class':'form-control','placeholder':'Your email',
            'pattern':"[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$"}),
            'subject': forms.TextInput(attrs={'class':'form-control','placeholder':'Subject','minlength':5}),
            'message':forms.Textarea(attrs={'class':'form-control','placeholder':'Message','rows':5, 'minlength':5}),
        }

events/forms.py
from django import forms 
from .models import Event

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['title', 'text', 'date', 'image']

        widgets = {
                'title': forms.TextInput(attrs={'class':'form-control', 'minlength':2,
                'placeholder':'Event Title'}),
                'text': forms.Textarea(attrs={'class':'form-control','placeholder':'Event Text','rows':5, 'minlength':5}),
                'date': forms.TextInput(attrs={'class':'form-control','placeholder':'Date','minlength':5, 'type': 'datetime-local'}), 
                'image': forms.FileInput(attrs={'class':'form-control'}),           
            }

contacts/views.py
from django.shortcuts import render
from django.views.generic import FormView
from .forms import ContactForm
from django.contrib import messages

# Create your views here.
# class ContactView(TemplateView):
#     template_name = 'contacts/contact.html'


class ContactView(FormView):
    template_name = 'contacts/contact.html'
    form_class = ContactForm
    #initial = {'key': 'value'}
    initial = {'name':'','email':'','subject':'','message':''}

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form, 'button': True})

    def post(self, request, *args, **kwargs):
        button = True
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            button= False
            messages.success(request, "Your message was sent!" )        
        else:       
            messages.error(request, "Error. Verify your data")     
        return render(request, self.template_name, {'form': form, 'button':button})    

    

events/views.py
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required

from .models import Event
from .forms import EventForm

# Create your views here.

class EventListView(ListView):    
    model = Event
@method_decorator(staff_member_required, name='dispatch')
class EventCreateView(SuccessMessageMixin, CreateView):
    model = Event
    form_class = EventForm
    success_message = 'Event was created successfully'
@method_decorator(staff_member_required, name='dispatch')
class EventUpdateView(SuccessMessageMixin, UpdateView):
    model = Event
    form_class = EventForm
    template_name_suffix = '_update_form'    
    success_message = 'Event was updated successfully'

@method_decorator(staff_member_required, name='dispatch')
class EventDeleteView(SuccessMessageMixin, DeleteView):
    model = Event
    success_url = reverse_lazy('events')
    success_message = "Event deleted"

trainers/views.py
from django.views.generic import ListView

from .models import Trainer

# Create your views here.

class TrainerListView(ListView):     
     model = Trainer

templates/mentor/contact.html
{% extends 'base.html' %} {% block title %}Contact{% endblock %}
{% block content %}
<main id="main">
  <!-- ======= Breadcrumbs ======= -->
  <div class="breadcrumbs" data-aos="fade-in">
    <div class="container">
      <h2>Contact Us</h2>
      <p>
        Est dolorum ut non facere possimus quibusdam eligendi voluptatem. Quia
        id aut similique quia voluptas sit quaerat debitis. Rerum omnis ipsam
        aperiam consequatur laboriosam nemo harum praesentium.
      </p>
    </div>
  </div>
  <!-- End Breadcrumbs -->

  <!-- ======= Contact Section ======= -->
  <section id="contact" class="contact">
    <div data-aos="fade-up">
      <iframe
        style="border: 0; width: 100%; height: 350px"
        src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12097.433213460943!2d-74.0062269!3d40.7101282!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb89d1fe6bc499443!2sDowntown+Conference+Center!5e0!3m2!1smk!2sbg!4v1539943755621"
        frameborder="0"
        allowfullscreen
      ></iframe>
    </div>

    <div class="container" data-aos="fade-up">
      <div class="row mt-5">
        <div class="col-lg-4">
          <div class="info">
            <div class="address">
              <i class="bi bi-geo-alt"></i>
              <h4>Location:</h4>
              <p>A108 Adam Street, New York, NY 535022</p>
            </div>

            <div class="email">
              <i class="bi bi-envelope"></i>
              <h4>Email:</h4>
              <p>info@example.com</p>
            </div>

            <div class="phone">
              <i class="bi bi-phone"></i>
              <h4>Call:</h4>
              <p>+1 5589 55488 55s</p>
            </div>
          </div>
        </div>

        <div class="col-lg-8 mt-5 mt-lg-0">
          <form action="" method="post" role="form" class="email-form" novalidate>
            {% csrf_token %}
            <div class="row">
              <div class="col-md-6 form-group">{{ contact_form.name }}</div>
              <div class="col-md-6 form-group mt-3 mt-md-0">{{ contact_form.email }}</div>
            </div>
            <div class="form-group mt-3">{{ contact_form.subject }}</div>
            <div class="form-group mt-3">{{ contact_form.message }}</div>

            {% if msg.text %}
              <div class="alert alert-{{msg.color}} my-3">
                <strong>{{ msg.text }}</strong> 
              </div>
            {% endif %} 
                
            <div class="text-center">
              <button type="submit" class="contact-button">Send Message</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
  <!-- End Contact Section -->
</main>
<!-- End #main -->
{% endblock %}

templates/mentor/course-details.html
{% extends 'base.html' %}
{% block title %}Courses{% endblock %}
{% block content %}
{% load static %}
  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs" data-aos="fade-in">
      <div class="container">
        <h2>Course Details</h2>
        <p>Est dolorum ut non facere possimus quibusdam eligendi voluptatem. Quia id aut similique quia voluptas sit quaerat debitis. Rerum omnis ipsam aperiam consequatur laboriosam nemo harum praesentium. </p>
      </div>
    </div><!-- End Breadcrumbs -->

    <!-- ======= Cource Details Section ======= -->
    <section id="course-details" class="course-details">
      <div class="container" data-aos="fade-up">

        <div class="row">
          <div class="col-lg-8">
            <img src="{{ course.image.url }}" class="img-fluid" alt="">
            <h3>{{ course.name }}</h3>
            <p>{{ course.text }}</p>
          </div>
          <div class="col-lg-4">

            <div class="course-info d-flex justify-content-between align-items-center">
              <h5>Trainer</h5>
              <p><a href="#">{{ course.trainer }}</a></p>
            </div>

            <div class="course-info d-flex justify-content-between align-items-center">
              <h5>Course Fee</h5>
              <p>${{ course.fee }}</p>
            </div>

            <div class="course-info d-flex justify-content-between align-items-center">
              <h5>Available Seats</h5>
              <p>{{ course.seats }}</p>
            </div>

            <div class="course-info d-flex justify-content-between align-items-center">
              <h5>Schedule</h5>
              <p>{{ course.schedule }}</p>
            </div>

          </div>
        </div>

      </div>
    </section><!-- End Cource Details Section -->

    <!-- ======= Cource Details Tabs Section ======= -->
    <section id="cource-details-tabs" class="cource-details-tabs">
      <div class="container" data-aos="fade-up">

        <div class="row">
          <div class="col-lg-3">
            <ul class="nav nav-tabs flex-column">
              <li class="nav-item">
                <a class="nav-link active show" data-bs-toggle="tab" href="#tab-1">Modi sit est</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" data-bs-toggle="tab" href="#tab-2">Unde praesentium sed</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" data-bs-toggle="tab" href="#tab-3">Pariatur explicabo vel</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" data-bs-toggle="tab" href="#tab-4">Nostrum qui quasi</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" data-bs-toggle="tab" href="#tab-5">Iusto ut expedita aut</a>
              </li>
            </ul>
          </div>
          <div class="col-lg-9 mt-4 mt-lg-0">
            <div class="tab-content">
              <div class="tab-pane active show" id="tab-1">
                <div class="row">
                  <div class="col-lg-8 details order-2 order-lg-1">
                    <h3>Architecto ut aperiam autem id</h3>
                    <p class="fst-italic">Qui laudantium consequatur laborum sit qui ad sapiente dila parde sonata raqer a videna mareta paulona marka</p>
                    <p>Et nobis maiores eius. Voluptatibus ut enim blanditiis atque harum sint. Laborum eos ipsum ipsa odit magni. Incidunt hic ut molestiae aut qui. Est repellat minima eveniet eius et quis magni nihil. Consequatur dolorem quaerat quos qui similique accusamus nostrum rem vero</p>
                  </div>
                  <div class="col-lg-4 text-center order-1 order-lg-2">
                    <img src="{% static 'img/course-details-tab-1.png' %}" alt="" class="img-fluid">
                  </div>
                </div>
              </div>
              <div class="tab-pane" id="tab-2">
                <div class="row">
                  <div class="col-lg-8 details order-2 order-lg-1">
                    <h3>Et blanditiis nemo veritatis excepturi</h3>
                    <p class="fst-italic">Qui laudantium consequatur laborum sit qui ad sapiente dila parde sonata raqer a videna mareta paulona marka</p>
                    <p>Ea ipsum voluptatem consequatur quis est. Illum error ullam omnis quia et reiciendis sunt sunt est. Non aliquid repellendus itaque accusamus eius et velit ipsa voluptates. Optio nesciunt eaque beatae accusamus lerode pakto madirna desera vafle de nideran pal</p>
                  </div>
                  <div class="col-lg-4 text-center order-1 order-lg-2">
                    <img src="{% static 'img/course-details-tab-2.png' %}" alt="" class="img-fluid">
                  </div>
                </div>
              </div>
              <div class="tab-pane" id="tab-3">
                <div class="row">
                  <div class="col-lg-8 details order-2 order-lg-1">
                    <h3>Impedit facilis occaecati odio neque aperiam sit</h3>
                    <p class="fst-italic">Eos voluptatibus quo. Odio similique illum id quidem non enim fuga. Qui natus non sunt dicta dolor et. In asperiores velit quaerat perferendis aut</p>
                    <p>Iure officiis odit rerum. Harum sequi eum illum corrupti culpa veritatis quisquam. Neque necessitatibus illo rerum eum ut. Commodi ipsam minima molestiae sed laboriosam a iste odio. Earum odit nesciunt fugiat sit ullam. Soluta et harum voluptatem optio quae</p>
                  </div>
                  <div class="col-lg-4 text-center order-1 order-lg-2">
                    <img src="{% static 'img/course-details-tab-3.png' %}" alt="" class="img-fluid">
                  </div>
                </div>
              </div>
              <div class="tab-pane" id="tab-4">
                <div class="row">
                  <div class="col-lg-8 details order-2 order-lg-1">
                    <h3>Fuga dolores inventore laboriosam ut est accusamus laboriosam dolore</h3>
                    <p class="fst-italic">Totam aperiam accusamus. Repellat consequuntur iure voluptas iure porro quis delectus</p>
                    <p>Eaque consequuntur consequuntur libero expedita in voluptas. Nostrum ipsam necessitatibus aliquam fugiat debitis quis velit. Eum ex maxime error in consequatur corporis atque. Eligendi asperiores sed qui veritatis aperiam quia a laborum inventore</p>
                  </div>
                  <div class="col-lg-4 text-center order-1 order-lg-2">
                    <img src="{% static 'img/course-details-tab-4.png' %}" alt="" class="img-fluid">
                  </div>
                </div>
              </div>
              <div class="tab-pane" id="tab-5">
                <div class="row">
                  <div class="col-lg-8 details order-2 order-lg-1">
                    <h3>Est eveniet ipsam sindera pad rone matrelat sando reda</h3>
                    <p class="fst-italic">Omnis blanditiis saepe eos autem qui sunt debitis porro quia.</p>
                    <p>Exercitationem nostrum omnis. Ut reiciendis repudiandae minus. Omnis recusandae ut non quam ut quod eius qui. Ipsum quia odit vero atque qui quibusdam amet. Occaecati sed est sint aut vitae molestiae voluptate vel</p>
                  </div>
                  <div class="col-lg-4 text-center order-1 order-lg-2">
                    <img src="{% static 'img/course-details-tab-5.png' %}" alt="" class="img-fluid">
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>
    </section><!-- End Cource Details Tabs Section -->

  </main><!-- End #main -->
{% endblock %}

templates/mentor/courses.html
{% extends 'base.html' %}
{% block title %}Courses{% endblock %}
{% block content %}
{% load static %}
  <main id="main" data-aos="fade-in">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs">
      <div class="container">
        <h2>Courses</h2>
        <p>Est dolorum ut non facere possimus quibusdam eligendi voluptatem. Quia id aut similique quia voluptas sit quaerat debitis. Rerum omnis ipsam aperiam consequatur laboriosam nemo harum praesentium. </p>
      </div>
    </div><!-- End Breadcrumbs -->

    <!-- ======= Courses Section ======= -->
    <section id="courses" class="courses">
      <div class="container" data-aos="fade-up">

        <div class="row" data-aos="zoom-in" data-aos-delay="100">
          {% for course in course_list %}
          <div class="col-lg-4 col-md-6 d-flex align-items-stretch">
            <div class="course-item">              
              <img src="{{ course.image.url }}" class="img-fluid" alt="...">
              <div class="course-content">
                <div class="d-flex justify-content-between align-items-center mb-3">
                  <h4>{{ course.category }}</h4>
                  <p class="price">${{ course.fee }}</p>
                </div>

                <h3><a href="{% url 'course-detail' course.id %}">{{ course.name }}</a></h3>
                <p>{{ course.brief }}</p>
                <div class="trainer d-flex justify-content-between align-items-center">
                  <div class="trainer-profile d-flex align-items-center">                    
                    <img src="{{ course.trainer.photo.url }}" class="img-fluid" alt="">
                    <span>{{ course.trainer }}</span>
                  </div>
                  <div class="trainer-rank d-flex align-items-center">
                    <i class="bx bx-user"></i>&nbsp;{{course.seats}}                    
                  </div>
                </div>
              </div>
            </div>
          </div> <!-- End Course Item-->
          {% endfor %}
        </div>
      </div>
    </section><!-- End Courses Section -->
  </main><!-- End #main -->
{% endblock %}
  

templates/mentor/events.html
{% extends 'base.html' %}
{% block title %}Events{% endblock %}
{% block content %}
{% load static %}
  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs" data-aos="fade-in">
      <div class="container">
        <h2>Events</h2>
        <p>Est dolorum ut non facere possimus quibusdam eligendi voluptatem. Quia id aut similique quia voluptas sit quaerat debitis. Rerum omnis ipsam aperiam consequatur laboriosam nemo harum praesentium. </p>
      </div>
    </div><!-- End Breadcrumbs -->

    <!-- ======= Events Section ======= -->
    <section id="events" class="events">
      <div class="container" data-aos="fade-up">        
        
        <div class="row">
          {% for event in event_list %}
          <div class="col-md-6 d-flex align-items-stretch">            
            <div class="card">
              <div class="card-img">
                <img src="{{ event.image.url }}" alt="...">
              </div>
              <div class="card-body">
                <h5 class="card-title"><a href="">{{ event.title }}</a></h5>
                <p class="fst-italic text-center">{{ event.date|date:"l, F dS"}} at {{event.date|time:"P"}}</p>
                <p class="card-text">{{ event.text }}</p>
              </div>
            </div>                        
          </div>  
          {% endfor %}                  
        </div>        
      </div>
    </section><!-- End Events Section -->

  </main><!-- End #main -->
{% endblock %}

templates/mentor/trainers.html
{% extends 'base.html' %}
{% block title %}Trainers{% endblock %}

{% block content %}
{% load static %}
  <main id="main" data-aos="fade-in">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs">
      <div class="container">
        <h2>Trainers</h2>
        <p>Est dolorum ut non facere possimus quibusdam eligendi voluptatem. Quia id aut similique quia voluptas sit quaerat debitis. Rerum omnis ipsam aperiam consequatur laboriosam nemo harum praesentium. </p>
      </div>
    </div><!-- End Breadcrumbs -->

    <!-- ======= Trainers Section ======= -->
    <section id="trainers" class="trainers">
      <div class="container" data-aos="fade-up">

        <div class="row" data-aos="zoom-in" data-aos-delay="100">
          {% for trainer in trainer_list %}
          <div class="col-lg-4 col-md-6 d-flex align-items-stretch">
            <div class="member">
              <img src="{{ trainer.photo.url }}" class="img-fluid" alt="">
              <div class="member-content">
                <h4>{{ trainer.first_name }} {{ trainer.last_name }}</h4>
                <span>{{ trainer.title }}</span>
                <p>
                  {{ trainer.brief }}
                </p>
                <div class="social">
                  <a href=""><i class="bi bi-twitter"></i></a>
                  <a href=""><i class="bi bi-facebook"></i></a>
                  <a href=""><i class="bi bi-instagram"></i></a>
                  <a href=""><i class="bi bi-linkedin"></i></a>
                </div>
              </div>
            </div>
          </div>          
          {% endfor %}
        </div>

      </div>
    </section><!-- End Trainers Section -->

  </main><!-- End #main -->
{% endblock %}  